[package]
name = "gb"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gb"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive", "string"] }
anyhow = "1"
thiserror = "2"
colored = "3"
dirs = "6"
glob-match = "0.2"
